apiVersion: v1
kind: Service
metadata:
  name: care-metrics-exporter
  labels:
    app.kubernetes.io/name: care-metrics-exporter
    app.kubernetes.io/component: metrics-exporter
    app.kubernetes.io/part-of: care
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: care-metrics-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP
