apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: care-backend-care-be-celery-worker
  namespace: care
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: care-backend-care-be-celery-worker
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 4
          periodSeconds: 15
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 900
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
